services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./static:/static
      - ./media:/media
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=host.docker.internal
      - DB_NAME=dbunimadapp
      - DB_USER=unimad_db_user
      - DB_PASSWORD=unimad_db_password
      - DB_PORT=5432
      - LINKEDIN_KEY=78g5a58sbwy81a
      - LINKEDIN_SECRET=PNJischnjmCxlZIw
      - SECRET_KEY=django-insecure-e@pd4ov^-b7%%93g(8s*-1lwdc7flcbrg0*1$5joqu(v3sni0&
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbunimadapp
      POSTGRES_USER: unimad_db_user
      POSTGRES_PASSWORD: unimad_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

